### PR TITLE
Intel quicky 2 to implement 1

### LINKED ISSUE #49: OAuth is always redirecting to localhost
**Describe the bug**
OAuth util has implemented a switch which recognises whether you are on localhost or not.
The correct config detail is chosen accordingly. That doesn't work correctly.

**To Reproduce**
1. Go to 'https://snek.at'
2. Click on 'Software Engineer'
3. Click on the GitHub icon and sign in

**Expected behavior**
The Github redirect should work on snek and localhost.

**Screenshots**
telegram-cloud-photo-size-4-5877248843328893730-y

**Desktop (please complete the following information):**
  - OS: MacOS, windows
  - Browser: safari, chrome

**Additional context**
- Ref: 🐍

### LINKED ISSUE #50: The OSM is not working with JavaScript compression
**Describe the bug**
The OSM uses the constructor name of a statement object as a reference to the database table name. This variant works without JS JavaScript compression.
After react-script build compresses the code, the OSM can no longer resolve the table names with the help of the model constructor.

**To Reproduce**
1. Go to 'https://snek.at/'
2. Login
3. Wait

**Expected behavior**
The page should load without errors. The caching must be carried out without falsifying data.

**Screenshots**
image

**Desktop (please complete the following information):**
  - OS: MacOS, Windows
  - Browser: chrome, safari

**Additional context**
- Ref: 🐍

### PR DESCRIPTION
**Pull request by schettn**
**Checklist:**

 
 - [x] Have you added an explanation of what your changes do and why you'd like them to be included?
 - [x] Have you updated or added documentation for the change?
 - [x] Have you tested your changes with successful results?

**Type of Changes:**

 
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] New feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change)

**What is the current behavior? (link to any open issues here)**
- Currently OAuth only works on development mode. #49
- Currently the intel does not worked on deployment mode.  #50
- Currently the intel creates page lagging. snek-at/front#145

**What is the new behavior (if this is a feature change)?**
- Now OAuth works on development and deployment mode. Closes #49 
- Now the intel works on deployment mode. Closes #50
- Now the page lagging is massively reduced. snek-at/front#145

**Other information**:
- Ref: 🐍

### CODE REVIEW

File: src/reducer/helper/profile.ts [hunk 1]
```diff
@@ -88,6 +92,7 @@ function mergedProfile() {
 
     return repository.render([]);
   });
```
Comment (kleberbaum) [inline src/reducer/helper/profile.ts:94]: Please add a newline.

File: src/reducer/helper/profile.ts [hunk 2]
```diff
@@ -124,6 +129,7 @@ function mergedProfile() {
 
     return organization.render([]);
   });
```
Comment (kleberbaum) [inline src/reducer/helper/profile.ts:131]: Please add a newline.

File: src/utils/github/converter.ts [hunk 3]
```diff
@@ -29,26 +33,29 @@ function run(rawData: any) {
...
   rawData.profile.organizations.edges.forEach((edge: any) => {
-    let organization = platform.createOrganization({
-      avatarUrl: edge.node.avatarUrl,
-      url: edge.node.url,
-      name: edge.node.login,
-      fullname: edge.node.name,
-      description: edge.node.description,
-    });
+    if (edge.node) {
+      let organization: models.Organization;
```
Comment (kleberbaum) [inline src/utils/github/converter.ts:40]: Please add a newline.
